### ISSUE TITLE
Unable to delete a storage volume in Ubuntu 16.10

### ISSUE THREAD

**Issue by lcorreia** [kimchi-project/kimchi#1122] opened 2017-03-20 18:53 UTC
A no clue message is showed:
Unable to delete storage volume file: /srv/dir.Details:

**Comment by alinefm** [comment] 2017-03-22 18:16
I could not reproduce it with the current upstream code. I will close it by now, please, feel free to reopen if the problem persists.

**Closed by alinefm** 2017-03-22 18:16 UTC
