### ISSUE TITLE
New UI shows Kimchi header section two times after session time out 

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/kimchi#758] opened 2015-11-17 08:51 UTC
Steps to reproduce:
1. Log in to Kimchi and click on one of the tab
2. Leave for some time (possibly couple of hours) to get the session time out. Again I am not sure how much time session will keep remain.
3. Try clicking any of other tab than existing opened one.

You will see the following screen. Ideally Kimchi logo (header section) would have shown only once. First header section should not be shown
![kimchi_session_timeout_issue](https://cloud.githubusercontent.com/assets/10830725/11206600/28882714-8d36-11e5-8e99-83635cf92a24.jpg)

**Comment by samhenri** [comment] 2015-12-07 19:17
I believe this issue was somehow "fixed" with the new navigation bar, but now it make my browser tab hang until it crashes. I'm able to reproduce the same behavior if I try to open a modal window after after a session time out.

**Comment by samhenri** [comment] 2016-01-04 14:51
@chandrureddy Hi Chandra, can you confirm if this is still happening with the new-ui?

**Comment by sstoppler** [comment] 2016-05-24 17:40
@chandrureddy -- would you mind retrying this?  I am not seeing this with the new UI.  Thanks!

**Comment by alinefm** [comment] 2016-06-02 02:26
I could not reproduce that in the last months so I will close this issue by now.
Please, reopen it if the problem persists.

**Closed by alinefm** 2016-06-02 02:26 UTC
Labels: bug, UI
