### ISSUE TITLE
Unable to start kimchid on Ubuntu 14.10

### ISSUE THREAD

**Issue by tbyehl** [kimchi-project/kimchi#613] opened 2015-03-13 20:42 UTC
I installed from the .deb and followed the instructions at http://kimchi-project.github.io/kimchi/downloads/

System is Ubuntu 14.10, current on updates.

```
root@san:~# uname -a
Linux san 3.16.0-31-generic #43-Ubuntu SMP Tue Mar 10 17:37:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
root@san:~# kimchid --host=0.0.0.0 --environment=development
Loading AptUpdate features.
[13/Mar/2015:16:41:34] ENGINE Listening for SIGHUP.
[13/Mar/2015:16:41:34] ENGINE Listening for SIGTERM.
[13/Mar/2015:16:41:34] ENGINE Listening for SIGUSR1.
[13/Mar/2015:16:41:34] ENGINE Bus STARTING
[13/Mar/2015:16:41:34] ENGINE Started monitor thread 'Autoreloader'.
[13/Mar/2015:16:41:34] ENGINE Serving on http://127.0.0.1:8010
*** Running feature tests ***
[13/Mar/2015:16:41:34] ENGINE Error in 'start' listener <bound method CapabilitiesModel._set_capabilities of <kimchi.model.config.CapabilitiesModel object at 0x7f148a589b10>>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/process/wspbus.py", line 205, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/lib/python2.7/dist-packages/kimchi/model/config.py", line 68, in _set_capabilities
    self.qemu_stream_dns = FeatureTests.qemu_iso_stream_dns()
  File "/usr/lib/python2.7/dist-packages/kimchi/model/featuretests.py", line 155, in qemu_iso_stream_dns
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

[13/Mar/2015:16:41:34] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/process/wspbus.py", line 243, in start
    self.publish('start')
  File "/usr/lib/python2.7/dist-packages/cherrypy/process/wspbus.py", line 223, in publish
    raise exc
ChannelFailures: OSError(2, 'No such file or directory')

[13/Mar/2015:16:41:34] ENGINE Bus STOPPING
[13/Mar/2015:16:41:34] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 8010)) shut down
[13/Mar/2015:16:41:34] ENGINE Stopped thread 'Autoreloader'.
[13/Mar/2015:16:41:34] ENGINE Bus STOPPED
[13/Mar/2015:16:41:34] ENGINE Bus EXITING
[13/Mar/2015:16:41:34] ENGINE Bus EXITED
```

**Comment by alinefm** [comment] 2015-03-16 14:44
@tbyehl How did you build the deb package?
Could you provide step by step on how to reproduce it?

**Comment by RainbowDashDC** [comment] 2015-05-18 06:29
Cannot reproduce myself, it's working fine for me.

**Comment by alinefm** [comment] 2015-09-21 15:34
I could not reproduce that. I am closing the issue by now.

**Closed by alinefm** 2015-09-21 15:34 UTC
