### ISSUE TITLE
Unable to list, add and edit templates

### ISSUE THREAD

**Issue by samhenri** [kimchi-project/kimchi#792] opened 2015-12-07 17:50 UTC
I'm unable to view any template in Templates tab. This is the current output in Google Chrome:

```GET https://10.10.71.85:8001/plugins/kimchi/templates 500 (Internal Server Error)```

HTTP/1.1 500 Internal Server Error
Server: nginx/1.4.7
Date: Mon, 07 Dec 2015 17:46:15 GMT
Content-Type: application/json;charset=utf-8
Content-Length: 1724
Connection: keep-alive
Content-Security-Policy: default-src 'self'
Set-Cookie: wok=b6679e53c8298d5f1a886fa89f6f115f7841eba6; expires=Mon, 07 Dec 2015 17:56:14 GMT; httponly; Path=/; secure

This is the response:

{
  "reason":"The server encountered an unexpected condition which prevented it from fulfilling the request.",
  "code":"500 Internal Server Error",
  "call_stack":"Traceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py\", line 670, in respond\n    response.body = self.handler()\n  File \"/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py\", line 217, in __call__\n    self.body = self.oldhandler(*args, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py\", line 61, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File \"/home/kimchi_master/wok/src/wok/control/base.py\", line 350, in index\n    return self.get(filter_params)\n  File \"/home/kimchi_master/wok/src/wok/control/base.py\", line 337, in get\n    resources = self._get_resources(flag_filter)\n  File \"/home/kimchi_master/wok/src/wok/control/base.py\", line 300, in _get_resources\n    res.lookup()\n  File \"/home/kimchi_master/wok/src/wok/control/base.py\", line 145, in lookup\n    self.info = lookup(*self.model_args)\n  File \"/home/kimchi_master/wok/src/wok/plugins/kimchi/model/templates.py\", line 145, in lookup\n    t = self.get_template(name, self.objstore, self.conn)\n  File \"/home/kimchi_master/wok/src/wok/plugins/kimchi/model/templates.py\", line 142, in get_template\n    return LibvirtVMTemplate(params, False, conn)\n  File \"/home/kimchi_master/wok/src/wok/plugins/kimchi/model/templates.py\", line 212, in __init__\n    VMTemplate.__init__(self, args, scan)\n  File \"/home/kimchi_master/wok/src/wok/plugins/kimchi/vmtemplate.py\", line 91, in __init__\n    pool_type = self._get_storage_type(disk['pool']['name'])\nKeyError: 'pool'\n"
}

**Comment by Truja** [comment] 2015-12-07 18:07
Working on this

**Comment by Truja** [comment] 2015-12-07 19:15
I just did the following test and was *not able* to reproduce the problem:

- Installed package kimchi-1.5.1-3.fc24.noarch and started.
- Opened Kimchi in a clean/private Firefox window
- Created two templates and modified their values (add cpu, more memory, etc)
- Closed Firefox and stopped Kimchi
- Updated and rebuild (distclean/autogen.sh/make) my Kimchi and Wok upstream local trees (master branches)
- Copied /var/lib/kimchi/objectstore into data directory of my Kimchi upstream tree
- Ran wokd with --environment=dev
At this point I could see this in the output:
-------------------------------------------------------------------------------------------------------
[rotru@localhost wok]$ sudo src/wokd --environment=dev
Plugin configuration file /home/rotru/Projetos/Upstream/wok/src/wok/plugins/ginger/ginger.conf doesn't exist.
Loading YumUpdate features.
WebSocket server settings:
  - Listen on :64667
  - Flash security policy server
  - Web server. Web root: /home/rotru/Projetos/Upstream/wok/ui/pages/websockify
  - SSL/TLS support
  - Deny non-SSL/TLS connections
  - proxying from :64667 to targets in /home/rotru/Projetos/Upstream/wok/src/wok/plugins/kimchi/data/vnc-tokens

Objectstore schema sucessfully upgraded.
2 'icon' entries upgraded in objectstore.
2 'storagepool' entries upgraded in objectstore.
2 'template' entries upgraded in objectstore.
...
----------------------------------------------------------------------------------
Notice the last line... its from my patch, updating the 2 templates entries.

- Then I opened a new clean/private Firefox window
- Opened Kimchi, can see new interface
- Went to Templates tab and WAS ABLE to see the 2 templates I had created before.

This is the DIFF of one of them:
-----------------------------------------------------------------------------------------------------------
--- /tmp/obj1   2015-12-07 16:54:09.277234474 -0200
+++ /tmp/obj2   2015-12-07 16:59:08.084504101 -0200
@@ -11,41 +11,42 @@
  "cdrom": "/var/lib/kimchi/isos/Fedora-Live-Workstation-x86_64-23-10.iso",
  "arch": "x86_64",
  "networks": ["default"],
- "icon": "images/icon-fedora.png",
+ "icon": "plugins/kimchi/images/icon-fedora.png",
  "os_distro": "fedora",
  "name": "fedora23.1449511500518",
  "cdrom_index": 2,
  "nic_model": "virtio",
- "disks": [{"index": 0, "format": "qcow2", "size": 5}],
+ "disks": [{"index": 0, "size": 5, "pool": {"type": "dir", "name": "/plugins/kimchi/storagepools/default"}, "format": "qcow2"}],
  "max_memory": 7926184,
  "disk_bus": "virtio",
  "os_version": "23",
- "storagepool": "/storagepools/default",
  "memory": 2048
 }
+1.5.1
------------------------------------------------------------------------------------------------

You can see that there is not "storagepool" anymore, "disks" were updated and there is the version.
So everything is as expected.

Can you please provide all the steps you are following ? How to reproduce, etc ?

**Comment by Truja** [comment] 2015-12-07 20:40
Ok, the root cause of this issue is that objectstore must be upgraded at once, and nevermore.

Kimchi has 3 upgrade scripts, which will run in sequence. But due to the commits timeline, the last script was committed some days later... so, if someone updated its local tree and upgraded the objectstore before the last script went upstream, this script will not run and you will see the error.

This is a development environment issue and the simplest way to workaround is:
 * remove kimchi/data/objectstore

**Comment by Truja** [comment] 2015-12-10 02:47
Please , close

**Closed** 2015-12-10 10:19 UTC
