### ISSUE TITLE
noVNC issues with some international keyboard characters

### ISSUE THREAD

**Issue by clnperez** [kimchi-project/kimchi#411] opened 2014-09-04 15:48 UTC
Someone noticed an issue using a French keyboard, so I pulled in the latest noVNC code to see if that helped. After testing with the rpm I built, the issue could still be created. It has been tested again with a Japanese keyboard:

Environment:                                                     
windows7, firefox 24.8.0 ESR (CCK-IBM)                              
.                                                                   
Test1 login kimchi and firefox with Japanese setting¨              
- Create new VM for installing SUSE11 SP3.                            
- Choose Japanese for install message and keyboard.                   
Result:
- can't input some character (ex: @ | ) in noVNC.      
- After installing, tried to input these character in gnome terminal
but the situation didn't change. 
- these characters work in ssh terminal.                                                    
                                                                  
Test2 login kimchi and firefox with English setting¨               
- Create new VM for installing SUSE11 SP3.                            
- Choose Japanese for install message and keyboard.                   
Result:
- This test created the same issue as test1.                          

Note: This has also been seen on Firefox 30, but I'll make sure they test using a newer Firefox from now on.

And the recreate using the French keyboard should happen soon. 

This is a noVNC issue, but it will take some help from us if we want to get it fixed there. I'm opening this issue to see if anyone on the Kimchi team has experience here and can help.

Leonardo commented in a noVNC issue here: https://github.com/kanaka/noVNC/issues/21#issuecomment-50192806

**Comment by Nukles** [comment] 2015-01-30 16:11
It seems to be not related to the keyboard layout on the host or the guest, but rather on the workstation where the browser is installed. Try changing the keyboard layout in your workstation's OS. You will see that other characters won't be available, but maybe those you're looking for are. We had the case with a Swiss German keyboard being unable to type / and =.

Another way to get around it, but only for RHEL guests, is to enter the console not with Kimchi but with virsh.

virsh ttyconsole guest01
or
virsh console guest01

Assuming your guest is called "guest01".

**Comment by krypto81** [comment] 2015-07-10 16:43
Hello, i have the same problem with german keyboard Layout so i did a few tests.
I created a vm in kimchi and tried to install ubuntu 14.04 lts with german keyboard settings in noVNC.
I can not enter special charakters like "ö", "@" so i shut down the vm and edited the kvm xml file on host.

The xml file is located in "/etc/libvirt/qemu/vm-name.xml"
I changed the Line
From:
 "<graphics type='vnc' port='-1' autoport='yes' listen='127.0.0.1' >"
To:
<graphics type='vnc' port='-1' autoport='yes' listen='127.0.0.1' keymap='de'>

and restarted libvirt-bin.

After that, i started the vm in kimchi and tried installing ubuntu again with german keyboard layout in noVNC.
All works fine after this modification in xml file.
Entering special german keyboard charakters working fine for this vm.
I think it should be similar for other keyboard layouts

My question, is it possible to add the parameter " keymap='de' " somwhere in template when creating a new virtual machine?

Thanks

**Comment by laggarcia** [comment] 2015-07-13 02:39
@krypto81, thanks for your feedback.

Some Kimchi users also reported this same workaround before (sadly it was not documented here). However, I heard that this workaround is not perfect: AltGr key usually has some issues and some users needed to map it to some other key with setxkbmap in order to make it accessible. Did you face any issue with AltGr?

Regarding your request to include the keymap in the graphics tag, I personally think this isn't a good solution for this issue. Kimchi is used from a web browser and should inherit whichever keyboard the system running this web browser is configured with. This is not something that should be limited in the template, IMO. A virtual machine can have multiple different keyboards configured and a user can easily switch from one keymap to another. If we have different users with different keyboards connected to their browsers, they would not be able to use virtual machines created from the same template because the template will wrongly limit which keyboard should connect to that virtual machine. As I said, I think the correct thing to do is to inherit the keyboard configured on the web browser and set it to the virtual machine, but I don't know if this can be done automatically. The browser would need to provide this information to Kimchi, and libvirt would need to allow this to be changed with the virtual machine running. And, even then, the AltGr issue would still exist.

**Comment by danielhb** [comment] 2016-05-11 10:27
@tavoc recently opened the same issue in WoK (https://github.com/kimchi-project/wok/issues/113) and I asked him to join the discussion here.

I have updates about this too. As @clnperez said when she first opened this bug, this is a problem in a component Kimchi uses called noVNC (https://github.com/kanaka/noVNC). They have a bug opened about it in https://github.com/kanaka/noVNC/issues/21 for a while now. I have proposed a fix for that bug in https://github.com/kanaka/noVNC/pull/596 .

What my fix does is give noVNC the capability of knowing it is dealing with a QEMU VNC server and, in that case, use a extension of the VNC protocol that implements a new keyboard event handler. This new handler allows the use of any keyboard layout in the VNC session as long as the keyboard layout of the guest matches the layout you want to use. And for the scope of this bug this is all I am going to say about it - please refer to the noVNC bug I mentioned above if you want to know the specifics.

I want to ask anyone interested in this bug to help test my pull request in noVNC - I am sure its community would appreciate the extra hands testing that code. However, I am not exactly sure how we can port my pull request to be used in Kimchi, aside from installing this pull request as a new noVNC package in the host. @laggarcia @alinefm any ideas?

**Comment by alinefm** [comment] 2016-06-01 15:16
Hi @danielhb 

Kimchi uses the standard novnc package provided by Linux distribution. So there is no way to make Kimchi uses it without having it included in a novnc package update.

Maybe we can try directly with the distribution: Fedora, Ubuntu... but I am not sure how it may happen.

**Comment by danielhb** [comment] 2016-06-01 15:51
Neither do I. The quickest route would be to get the fix accepted in upstream noVNC, then the distros would be getting it eventually. It would be extremely, enormously difficult to push the fix in the noVNC distribution of the distros without having it upstreamed in noVNC.

I actually think it's easier to try to push this kind of fix to upstream spice-html5 (which would include me learning a brand new protocol, making the fix, contributing it to their community, getting accepted ...) than to convince the noVNC Ubuntu package maintainer to "hey, this is my noVNC fix to the non-US keyboard. Upstream noVNC does not have it and have no ETA of including it. Can you please push it to the official Ubuntu noVNC package and maintain it by yourself?" . I don't think this is even a real possibility.

**Comment by danielhb** [comment] 2016-08-29 17:35
I am very happy to announce that the fix I've sent to noVNC was accepted today. The related bug kanaka/noVNC#21  was fixed as well. 

As such, I am closing this bug here. Thanks!

**Closed by danielhb** 2016-08-29 17:35 UTC
Labels: bug

**Comment by danielhb** [comment] 2016-08-29 19:09
Disclaimer: this does not mean that the problem is magically fixed in the current noVNC packages. The fix will be part of a new noVNC release, which must be accepted by each distro.

However, anyone can now download the current noVNC master code, install it and have the keyboard working :)

**Comment by Trolldemorted** [comment] 2016-12-07 19:54
@danielhb could you elaborate on how to install noVNC from the sources (and marry it to kimchi)?

we are using german keyboard layouts and we got no |, no @, no -, no nothing out of the box.
