### ISSUE TITLE
Guest name restrictions to be handled while creation itself

### ISSUE THREAD

**Issue by abhiramkulkarni** [kimchi-project/kimchi#679] opened 2015-07-03 06:22 UTC
1)Create a guest with space in its name. Created "test space"
2)Try to start this VM, it will not allow saying the name is invalid.
![screenshot from 2015-07-03 11 49 05](https://cloud.githubusercontent.com/assets/12495213/8493571/bbdfd13e-2179-11e5-95b8-bfbdc838a437.png)

Suggestion :- While creating the guest itself we should not allow name with space or while guest with space in name should be able to start.

**Comment by cd1** [comment] 2015-07-03 11:29
This is a known libvirt-related issue which happens on Fedora systems.

This is a duplicate of #450, so please follow up the discussion on that issue.

**Closed by cd1** 2015-07-03 11:29 UTC
