### ISSUE TITLE
Destination field not showing correct when there is no interface available

### ISSUE THREAD

**Issue by biancafc** [kimchi-project/kimchi#1118] opened 2017-03-17 19:45 UTC
I've seen this problem since the last release, when I go to Destination field, the selection menu is not showing as properly:

<img width="667" alt="screen shot 2017-03-17 at 16 44 42" src="https://cloud.githubusercontent.com/assets/6681745/24060231/1a7b4d2a-0b31-11e7-95ba-19afa75850a0.png">

I have to use keyboard to choose the option in the menu.

**Comment by alinefm** [comment] 2017-03-27 14:02
Hi @biancafc 

I could not reproduce that with the current upstream code + Chrome or Fiferox.
What I noticed is when there is no interface available I got a similar view of you. I will do a patch to display a message informing user there is no interface available.

**Comment by alinefm** [comment] 2017-04-04 16:24
Fixed by ca66c7c0dfccb9ddf7e267d0a8a4737a347bbf08

**Closed by alinefm** 2017-04-04 16:24 UTC
