### ISSUE TITLE
Logical storage pool is not getting deleted by Undefine operation from kimchi UI.

### ISSUE THREAD

**Issue by pawankg** [kimchi-project/kimchi#681] opened 2015-07-06 04:27 UTC
Logical storage pool is not getting deleted by Undefine operation from kimchi UI.

Work Environment:
Distributor ID: Ubuntu
Description: Ubuntu 14.04.2 LTS
Release: 14.04
Codename: trusty

Steps to reproduce:
1. Create a device (/dev/dasdb2) on local machine.
2. Go to tab "Storage" from kimchi UI.
3. Click on + sign in upper right hand corner to add storage pool.
4. Under "Define a new storage pool" menu:
- Give 'Storage Pool Name' as test_logical_pool.
- In 'Storage Pool Type', select logical from drop down menu.
- In 'device' select the device created above.
5. After creation of storage pool, go to Actions -> Activate
6. Then go to Actions -> Deactivate, so as to deactivate the storage pool before its deletion.
7. Then go to Actions -> Undefine, for deleting the test_logical_pool created above.
8. Again repeat steps 3 and 4 to create a logical strorage pool with same name "test_logical_pool". Error is seen that a pool with this name already exists. 
9. If I am checking the same from command line using pvdisplay or vgdisplay command, then also I can see that pool exists even after undefine operation. The output for the same is given below:

--- Physical volume ---
  PV Name               /dev/dasdb2
  VG Name               test_logical_pool
  PV Size               4.58 GiB / not usable 3.50 MiB
  Allocatable           yes
  PE Size               4.00 MiB
  Total PE              1171
  Free PE               1171
  Allocated PE          0
  PV UUID               YUavYx-Tx3l-W3gh-gLgP-SBAq-1yjj-3jzSTn

**Comment by laggarcia** [comment] 2015-07-06 16:03
My understanding is that this is working as designed. Libivirt does not delete logical pools when they are undefined. For different types of pools libvirt can act in different ways, as they have different underneath characteristics. You probably don't want to loose all your data because you undefined a storage pool.

**Comment by pawankg** [comment] 2015-07-07 06:36
Thanks for input. Below are some couple of inputs and questions:

1) I think logical storage pool DELETE API should not be DELETE instead should be POST action "undefine" with explanation that undefine will just undefine storage pool from kimchi but does not delete it from the system.
2) As a kimchi user how can I reuse the undefined logical storage pool. 
    As we are not deleting, so we cannot create logical storage pool with same name any more till it is not deleted from system.
3) Do you think for such storage pool, we should have a delete option to delete it from system (with warning of data deletion), so that as a system admin I do not need to have command to delete it.

**Comment by alinefm** [comment] 2015-09-21 19:01
Hi @pawankg 

1) The REST API methods are not related on what the application does in the system but how the action acts in the resource.
The DELETE method is to delete the resource from its collection. When calling this method in a logical pool it is deleted from the storage pools collection and also from libvirt point of view.

2) There is a feature request in our backlog related to create a logical pool based on an existing LVM (https://github.com/kimchi-project/kimchi/wiki/Todo-Backlog)
About not being able to reuse the previous pool name, AFAIU it is a libvirt limitation. There is no way to specify the LVM name different from the pool name.

3) It would be part of LVM management, ie, for host management. I think there is a similar feature request for Ginger (Kimchi plugin for host managament). Please, take a look at: https://github.com/kimchi-project/ginger

I will close this issue as it is working as designed.

**Closed by alinefm** 2015-09-21 19:01 UTC
