### ISSUE TITLE
Creation of the Bridge Network with vlan tag fails for both enable/disable of NetworkManager

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/kimchi#650] opened 2015-06-03 13:23 UTC
Creation of the Bridge Network with vlan tag fails for both enable/disable of NetworkManager

Work environment:
[ network-scripts]$ cat /etc/fedora-release 
Fedora release 21 (Twenty One)
[network-scripts]$ uname -a
Linux chandra.localdomain 3.19.5-200.fc21.x86_64 #1 SMP Mon Apr 20 19:51:56 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Steps to to reproduce:
Scenario 1: NetworkManager enabled/running.
1. Click Network tab
2. Click on "+" button to create new network
    It provided nice information "The bridged VLAN tag may not work well with NetworkManager enabled. You should consider disabling it"

Inputs provided:
"Network name" = nwbridge
Network Type = Bridged: Virtual machines are connected to physical network directly
Destination = enp0s3
 Enable VLAN  = 1031
1. click  "create"
   Got an error : 
   "internal error: failed to create (start) interface kbenp0s3-1031: failed to execute external program - Running 'ifup enp0s3.1031' failed with exit code 4: Error: Connection activation failed: Master connection not found or invalid: internal error: Running 'ipfup enp0s3.1031' failed with exit code 4: Error: Connection activation failed: Master connection not found or invalid stop"

Scenario 2: NetworkManager disabled/stopped.
Deactivated the Network Manger by : 
sudo systemctl disable NetworkManager.service
sudo systemctl stop NetworkManager.service
1. Click Network tab
2. Click on "+" button to create new network
   Inputs provided:
   "Network name" = nwbridge
   Network Type = Bridged: Virtual machines are connected to physical network directly
   Destination = enp0s3
   Enable VLAN  = 1032
3. click  "create"
   Got an error : 
   The Sercver encoutered an unexpected condition which prevented it from fulfilling the request.

Am I missing some thing here ?

Additional observation's were as follows:

Clean up or Modification of the created interface
1. In above failure cases I noticed that it created VLAN's enp0S3.1031, enp0S3.1032 as well as bridges enp0s3-1031 and enp0s3-1032.
2. Ideally it could have deleted the VLAN's/brdiges created  in case of failure or may be a way in helping them to bring up ie. modify the created bridge ???

Can not check/select the  check box "Enable VLAN" if you have bridges available along with physical interface.
For example after I tried two scenario's mentioned above, Destination select box shown the interfaces "enp0s3-1031, enp0s3, enp0s3-1032" to be selected. I tried to select main interface enp0s3 and wanted to check the check box "Enable VLAN" but noticed that I can not check it.

Attached here screen shot kimchi-network-bridge.jpg for your reference (Note: screen shot is from different machine where main interface is enp0S23)
![kimchi-network-bridge](https://cloud.githubusercontent.com/assets/10830725/7966801/08f716b4-0a44-11e5-89fd-28d97e941596.jpg)

Also for displaying the interface information for the selection box "Destination", what was command used ?
Thanks in advance.

**Comment by chandrureddy** [comment] 2015-06-03 17:30
Additional observation's
![kimchi-network-bridge](https://cloud.githubusercontent.com/assets/10830725/7966801/08f716b4-0a44-11e5-89fd-28d97e941596.jpg)
 were as follows:

Clean up or Modification of the created interface
1. In above failure cases I noticed that it created VLAN's enp0S3.1031, enp0S3.1032 as well as bridges enp0s3-1031 and enp0s3-1032.
2. Ideally it could have deleted the VLAN's/brdiges created  in case of failure or may be a way in helping them to bring up ie. modify the created bridge ???

Can not check/select the  check box "Enable VLAN" if you have bridges available along with physical interface.
For example after I tried two scenario's mentioned above, Destination select box shown the interfaces "enp0s3-1031, enp0s3, enp0s3-1032" to be selected. I tried to select main interface enp0s3 and wanted to check the check box "Enable VLAN" but noticed that I can not check it.

Attached here screen shot kimchi-network-bridge.jpg for your reference (Note: screen shot is from different machine where main interface is enp0S23)

Also for displaying the interface information for the selection box "Destination", what was command used ?

**Comment by chandrureddy** [comment] 2015-06-08 18:06
Is there a way I could clean up all the VLAN's/brdiges created in above failure cases ???
Any easiest way would be appreciated.

**Comment by sureshab** [comment] 2015-08-26 08:24
Hi,
Continuing on Scenario 2: 
NetworkManager disabled/stopped.
Deactivated the Network Manger by :
sudo systemctl disable NetworkManager.service
sudo systemctl stop NetworkManager.service

1. Click Network tab
2. Click on "+" button to create new network Inputs provided: "Network name" = br4 Network Type = Bridged: Virtual machines are connected to physical network directly Destination = enp0s3 Enable VLAN = 4
3. click "create" Got an error : The Sercver encoutered an unexpected condition which prevented it from fulfilling the request.

After this the network page loads with error - "The server encountered an unexpected condition which prevented it from fulfilling the request."
and list of networks will not be loaded in network tab.
![screenshot from 2015-08-26 12 40 13](https://cloud.githubusercontent.com/assets/12499230/9487495/ab355796-4bef-11e5-9a87-2ab07ae49e67.png)

it does create ifcfg-kbenp0s3-4 and ifcfg-enp0s3.4  files in /etc/sysconfig/network-scripts.

If I bring up kbenp0s3-4 and enp0s3.4 using ifup or start networkmanager (sudo systemctl start NetworkManager.service and sudo systemctl enable NetworkManager.service) command the network page will be loaded without any  error. 
![screenshot from 2015-08-26 12 46 00](https://cloud.githubusercontent.com/assets/12499230/9487559/73879484-4bf0-11e5-958d-e654591965a1.png)



Question's to be thought through:
1. Why network tab goes blank irrespective of the individual network operation fails ?
2. What was the history behind disabling the network manager ? I suppose Kimchi should not stop end user from using other network tools again at the same time tool should easily pick up any configuration done out side of the tool. 
3. Are we advising end user to block NetworkManager permanently ? or only in certain circumstances we ask user to disable temporarily ?, Let us say if we ask to disable NetworkManger then what will happen to the code which is referring nmcli as well in kimchi. 
Error log found in this case:
[21/Aug/2015:19:23:44] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/kimchi/control/base.py", line 330, in index
    return self.create(parse_request(), *args)
  File "/usr/lib/python2.7/site-packages/kimchi/control/base.py", line 267, in create
    return res.get()
  File "/usr/lib/python2.7/site-packages/kimchi/control/base.py", line 215, in get
    self.lookup()
  File "/usr/lib/python2.7/site-packages/kimchi/control/base.py", line 140, in lookup
    self.info = lookup(*self.model_args)
  File "/usr/lib/python2.7/site-packages/kimchi/model/networks.py", line 263, in lookup
    'vms': self._get_vms_attach_to_a_network(name),
  File "/usr/lib/python2.7/site-packages/kimchi/model/networks.py", line 295, in _get_vms_attach_to_a_network
    for dom in conn.listAllDomains(0):
  File "/usr/lib/python2.7/site-packages/kimchi/model/libvirtconnection.py", line 66, in wrapper
    ret = f(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 4658, in listAllDomains
    for domptr in ret:
IOError: [Errno 19] No such device

rc: 8 error: Error: NetworkManager is not running.
 returned from cmd: nmcli dev status
rc: 8 error: Error: NetworkManager is not running.
 returned from cmd: nmcli dev status
rc: 8 error: Error: NetworkManager is not running.
 returned from cmd: nmcli dev status
rc: 8 error: Error: NetworkManager is not running.
 returned from cmd: nmcli dev status

**Comment by lcorreia** [comment] 2016-01-04 20:18
Tried this with Fedora 23 x86_64. My feedback:

Scenario 1: it is still reproducible, but there is a warning message in virtual network creation pop-up asking to disable Network Manager.

Scenario 2: virtual network was created without an internal server error. But system network is not coming up after a reboot. A network restart after boot could solve it.

**Comment by alinefm** [comment] 2016-03-14 20:26
HI @chandrureddy 

Could you verify on Scenario 2 if restarting wokd service solves the issue?
I reported an issue related to that some time ago #858

**Comment by alinefm** [comment] 2017-03-27 17:09
I am unable to reproduce that with the current upstream code.
I needed to disable NetworkManager to be able to create a bridged VLAN network but it worked as expected.
I am closing this issue by now. Please, reopen if the problem persists to you.

**Closed by alinefm** 2017-03-27 17:09 UTC
Labels: bug
