### ISSUE TITLE
Kimchi cannot list repositories

### ISSUE THREAD

**Issue by lvroyce** [kimchi-project/kimchi#535] opened 2014-12-04 08:40 UTC
### Description
Kimchi cannot list repositories on Ubuntu 14.10

### Expected result
Repository listed in host tab

### Actual result
Backend failed to provide repository list and threw error 500 with:

reason: "KCHREPOS0025E: Unable to retrieve repository information. Details: 'E:Not locked'"
code: "500 Internal Server Error"
call_stack: "Traceback (most recent call last): File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond response.body = self.handler() File "/usr/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 217, in __call__ self.body = self.oldhandler(*args, **kwargs) File "/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__ return self.callable(*self.args, **self.kwargs) File "/usr/lib/python2.7/dist-packages/kimchi/control/base.py", line 337, in index raise cherrypy.HTTPError(500, e.message) HTTPError: (500, u"KCHREPOS0025E: Unable to retrieve repository information. Details: 'E:Not locked'") "

**Comment by danielhb** [comment] 2015-01-15 12:10
I can't reproduce this bug. Is there any special conditions not mentioned in the first post? Maybe aptitude was running at the same time, holding some kind of lock to the repos?

**Comment by alinefm** [comment] 2015-03-11 20:12
@danielhb @lvroyce it was fixed by b529c0cd876d18ea6d3bee1b809979b785bbcb51

**Closed by alinefm** 2015-03-11 20:12 UTC
Labels: bug

**Comment by cd1** [comment] 2015-03-11 20:26
This is a duplicate of issue #512.
