### ISSUE TITLE
Host: Debug Report, Download should be disabled on iPad(iPad Safari)

### ISSUE THREAD

**Issue by YuXinHuo** [kimchi-project/kimchi#499] opened 2014-12-02 08:08 UTC

**Comment by cd1** [comment] 2015-03-25 13:47
We're closing this issue for lack of information. If someone is able to reproduce it and provide more details to us, we will reopen it.

**Closed by cd1** 2015-03-25 13:47 UTC
Labels: NEEDINFO

**Comment by lvroyce** [comment] 2015-04-01 09:49
Please reopen this one:
Backend returns 200:
9.115.122.173 - - [01/Apr/2015:17:47:33] "GET /data/debugreports/Ac.tar.xz HTTP/1.0" 200 5754660 "https://9.115.122.170:8001/" "Mozilla/5.0 (iPad; CPU OS 8_0 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12A365 Safari/600.1.4"

But safari browser report:
Safari cannot download this file.

**Comment by cd1** [comment] 2015-04-02 20:06
I'm not very familiar with how things work on iOS, but AFAIK you cannot download anything to an iOS device itself - even though the download was sent by the server, as seen by the return code 200. You can, however, "open" a remote file with an appropriate app. There's [an interesting topic on Stack Exchange](http://apple.stackexchange.com/questions/25678/downloading-and-uploading-files-through-safari-ios) discussing that behavior. Please correct me if I'm wrong.

With that said, I don't see what we can do to solve this issue. There's no way to detect if an iOS device will handle the debug report file download correctly. And we can't disable that feature entirely for iOS users because some of them might have Google Drive/Dropbox/something which handles that file type nicely.

So I suggest leaving this as it is. In the case you tested, Safari couldn't download the file because the iOS device didn't have an app to handle that type of file, and there's no way for us to know that.

**Comment by lvroyce** [comment] 2015-04-03 07:49
ACK
