### ISSUE TITLE
No Plugins Currently Installed Message

### ISSUE THREAD

**Issue by chosen010** [kimchi-project/kimchi#747] opened 2015-10-31 02:46 UTC
Went through the installation readme and wokd fires up but upon login with root, presented with the message that no plugins currently installed with links to kimchi and ginger that go back to the original readme.

**Comment by chandrureddy** [comment] 2015-10-31 11:59
Have installed the plugins along with wokd ?

Basically installing the code at the source code level (https://github.com/kimchi-project/kimchi) would install only wokd basica frame work.

Installing plug in kimchi try as per readme mentioned in bleow URL:
https://github.com/kimchi-project/kimchi/tree/master/src/wok/plugins/kimchi
1. install dependancies
2. follow build and install instructions
$ cd plugins/kimchi
For openSUSE 13.1:
$ ./autogen.sh --with-spice-html5
Otherwise:
$ ./autogen.sh --system
$ make
$ sudo make install

Installing plug in ginger base try as per readme mentioned in bleow URL:
https://github.com/kimchi-project/kimchi/tree/master/src/wok/plugins/gingerbase
1. install dependancies
2. follow build and install instructions
$ cd plugins/gingerbasae
$ ./autogen.sh --system
$ make
$ sudo make install   # Optional if running from the source tree

Installing plug in ginger try as per readme mentioned in bleow URL:
https://github.com/kimchi-project/ginger
1. install dependancies
2. follow build and install instructions
$ ./autogen.sh --system
$ make
$ sudo make install   # Optional if running from the source tree

**Comment by mcvax** [comment] 2015-11-03 11:45
I have the same problem running Centos 7.

I have:
1. Installed all dependencies listed here: https://github.com/kimchi-project/kimchi
2. Cloned the repository with plugins using git clone --recursive https://github.com/kimchi-project/kimchi.git
3. Built Wok using:
   $ ./autogen.sh --system
   $ make
   $ sudo make install
4. Gone into the /kimchi/src/wok/plugins/kimchi directory and run:
   $ ./autogen.sh --system
   $ make
   $ sudo make install
5. Performed the same commands in the /kimchi/src/wok/plugins/ginger and /kimchi/src/wok/plugins/gingerbase directories

After restarting the Wok service Wok works fine, I can see the basic system info (I assume from Ginger) but nothing else.

The /var/log/wok/wok-error.log file has the following two lines in it:

    Failed to import plugin plugins.kimchi.KimchiRoot, error: Class plugins.kimchi.KimchiRoot can not be imported, error: No module named magic
    Failed to import plugin plugins.ginger.Ginger, error: Class plugins.ginger.Ginger can not be imported, error: No module named magic

I assume they are the cause?

Thanks

Chris

**Comment by mcvax** [comment] 2015-11-03 11:50
Just answered my own question.  python-magic now appears to be required.

Fixed by:

    yum python-magic

**Comment by alinefm** [comment] 2015-12-03 14:29
Closing this issue based on last comment

**Closed by alinefm** 2015-12-03 14:29 UTC
