### ISSUE TITLE
Error usage of feature tests on model tests

### ISSUE THREAD

**Issue by lvroyce** [kimchi-project/kimchi#580] opened 2015-02-03 07:04 UTC
## Description
Some feature tests count on a running kimchi server: qemu_supports_iso_stream, qemu_iso_stream_dns, so they cannot be used for model tests

**Comment by cd1** [comment] 2015-02-17 14:18
Isn't this a duplicate of issue #579?

**Comment by lvroyce** [comment] 2015-03-11 08:57
No, they are different issues, 579 means qemu_iso_stream_dns function is implemented wrong. This means we cannot use these two functions in feature tests. Please reopen.

**Comment by cd1** [comment] 2015-03-13 14:17
Fixed by d5e780038940814254361da57c4459ce437637f7.

**Closed by cd1** 2015-03-13 14:17 UTC
Labels: bug
