### ISSUE TITLE
Ubuntu: generating error report fails

### ISSUE THREAD

**Issue by lvroyce** [kimchi-project/kimchi#609] opened 2015-03-12 09:22 UTC
##  Reproduce
    Click debug report generating button
##  Expected result
    debug report generated
## Actual result
rc: 1 error: Traceback (most recent call last):
  File "/usr/bin/sosreport", line 23, in <module>
    main(sys.argv[1:])
  File "/usr/share/sosreport/sos/sosreport.py", line 1183, in main
    sos.execute()
  File "/usr/share/sosreport/sos/sosreport.py", line 1167, in execute
    self.html_report()
  File "/usr/share/sosreport/sos/sosreport.py", line 1090, in html_report
    rfd.write(html)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 3980-3985: ordinal not in range(128)
 returned from cmd: sosreport --batch --name=a
Error in async_task 4
Error in async_task 4
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/kimchi/asynctask.py", line 70, in _run_helper
    self.fn(cb, opaque)
  File "/usr/lib/python2.7/dist-packages/kimchi/model/debugreports.py", line 82, in sosreport_generate
    'err': retcode})
OperationFailed: KCHDR0003E: Unable to create debug report a. Details: 1.

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/kimchi/asynctask.py", line 70, in _run_helper
    self.fn(cb, opaque)
  File "/usr/lib/python2.7/dist-packages/kimchi/model/debugreports.py", line 82, in sosreport_generate
    'err': retcode})
OperationFailed: KCHDR0003E: Unable to create debug report a. Details: 1.

**Comment by cd1** [comment] 2015-03-12 13:41
Please, run the following command:

```
$ sudo sosreport --batch --name=test-report
```

And post the output here. We need to check if this issue is a duplicate of #511.

**Comment by alinefm** [comment] 2015-03-16 16:19
@cd1 @lvroyce I was able to generate the sosreport on Ubuntu 14.10

Check the command output below.

alinefm@alinefm:~$ sudo sosreport --batch --name=test-report
[sudo] password for alinefm: 

sosreport (version 3.1)

This command will collect diagnostic and configuration information from
this Ubuntu system and installed applications.

An archive containing the collected information will be generated in
/tmp and may be provided to a Ubuntu support representative.

Any information provided to Ubuntu will be treated in accordance with
the published support policies at:

  http://www.ubuntu.com/

The generated archive may contain data considered sensitive and its
content should be reviewed by the originating organization before being
passed to any third party.

No changes will be made to system configuration.


 Running plugins. Please wait ...

  Running 69/69: xfs...              .        
Creating compressed archive...

Your sosreport has been generated and saved in:
  /tmp/sosreport-test-report-20150316124524.tar.xz

The checksum is: 0d585348524700d07c30fb2f16dc06b9

Please send this file to your support representative.

**Comment by lvroyce** [comment] 2015-03-17 07:48
the command-line out put is right here, while kimchi still  *raise exception* when running, exception message is as above
royce@ubuntu:/etc/kimchi$ sudo sosreport --batch --name=a

sosreport (version 3.1)

This command will collect diagnostic and configuration information from
this Ubuntu system and installed applications.

An archive containing the collected information will be generated in
/tmp and may be provided to a Ubuntu support representative.

Any information provided to Ubuntu will be treated in accordance with
the published support policies at:

  http://www.ubuntu.com/

The generated archive may contain data considered sensitive and its
content should be reviewed by the originating organization before being
passed to any third party.

No changes will be made to system configuration.


 Running plugins. Please wait ...

  Running 68/68: xfs...              .        
Creating compressed archive...

Your sosreport has been generated and saved in:
  /tmp/sosreport-a-20150317154500.tar.xz

The checksum is: 3f09e403a38593cee05a6ebed04e20a6

Please send this file to your support representative.

**Comment by alinefm** [comment] 2015-03-17 15:01
@lvroyce @cd1 Strange because both works for me: from command line and through Kimchi.

**Comment by cd1** [comment] 2015-03-17 15:05
@lvroyce , could you try to reproduce this issue on Ubuntu 14.10? We only support the latest version of each distro.

**Comment by cd1** [comment] 2015-03-25 13:49
@lvroyce can reproduce this issue on Ubuntu 14.10.

**Comment by alinefm** [comment] 2015-09-21 15:31
I am not able to reproduce it on Ubuntu 15.04.
I will close this bug.

**Closed by alinefm** 2015-09-21 15:31 UTC
Labels: bug
