### ISSUE TITLE
WOK:  Firmware update feature is getting displayed on x86 architecture

### ISSUE THREAD

**Issue by jay-katta** [kimchi-project/kimchi#709] opened 2015-07-17 11:57 UTC
Environment: x86
Operating system: Ubuntu
Browser: Mozilla Firefox
Steps performed:
1. Installed WOK (https://github.com/kimchi-project/kimchi/tree/wok)
2. Installed kimchi-wok plugin
3. Installed ginger-wok plugin
2. Started wokd daemon
3. From browser launched https://127.0.0.1:8001
4. Login screen displayed
5. Entered userid and password
6. WOK web page displayed with Kimchi and Ginger tabs
7. Toggled between Administration tab(Ginger) and any Kimchi plugin tab

Problem: Power (ppc) firmware update feature is getting displayed

![710ae779c18034dd](https://cloud.githubusercontent.com/assets/12508158/8746620/d6bed6f0-2ca8-11e5-91a5-23a8ff3ed529.jpg)

**Comment by samhenri** [comment] 2015-07-21 14:53
Have you switched your Ginger branch to ginger_wok? Based on your screenshot it seems that jQuery-Ui wasn't loaded because all the panels are collapsed. The Firmware Update panel is loaded and rendered in the screen regardless of the architecture and then it is hidden by JavaScript.

**Comment by jay-katta** [comment] 2015-07-22 13:11
yes, I have applied ginger_wok branch..

**Comment by lcorreia** [comment] 2015-08-04 19:02
I cannot reproduce this in my Ubuntu 15.04.

**Comment by alinefm** [comment] 2015-10-22 17:21
I am moving this issue to ginger project as it is not related to Kimchi community.
Please, make any update on it: https://github.com/kimchi-project/ginger/issues/30

**Closed by alinefm** 2015-10-22 17:21 UTC
