### ISSUE TITLE
Kimchi is searching for 'undefined' VM

### ISSUE THREAD

**Issue by sstoppler** [kimchi-project/kimchi#968] opened 2016-06-27 22:13 UTC
I was changing between GUESTS and TEMPLATES tabs quickly.

Suddenly I received this error message:
KCHVM0002E: A máquina virtual undefined não existe    -->>   ("Guest undefined does not exist")
from request: "GET /plugins/kimchi/vms/undefined/hostdevs HTTP/1.0" 404 513 "https://kop5:8001/"

Then I see in firebug log, right after the request, that kimchi.guestElem is undefined error, from:
 kimchi.min.js line 2859

Just some more information:

1- I have checked the GET /VMS return and backend is sending all machines properly. There is no VM named 'undefined'  =]

2- Switching among tabs and opening modal (edit/add new, etc) I could notice two more UNDEFINED variables:

     TypeError: templateStr is undefined
           return templateStr.replace(tag, function(matchResult, express) {
           wok.min...11659.0 (line 2665, col 5)

     TypeError: kimchi.isoInfo is undefined
           if (!kimchi.isoInfo[isoId]) {
           kimchi.min   line 6162

**Comment by samhenri** [comment] 2016-07-21 17:10
Hi, I was unable to reproduce the first error "GET /plugins/kimchi/vms/undefined/hostdevs", probably because the PCI passthrough issue already fixes it. I'm trying to reproduce the other errors but I believe this is a variable scope issue. Even if I'm unable to reproduce it here I can force this error and make some workarounds to prevent it. I'm working on it.

**Comment by samhenri** [comment] 2016-07-22 19:35
Sent a patch to ML to fix the first issue in Guests and Templates (undefined variables when switching tabs). Was not able to reproduce the second part of the issue (opening modal windows) as they would not throw any error or warning messages on the console.

Like the first error, I believe this may happen when the browser window is between a loop refreshing a list and reassigning variable values and the user switches to another tab and the browser can't find the HTML object the function was looking for and then throws the undefined error.

**Comment by sstoppler** [comment] 2016-07-25 18:24
Requested for patch to be resent as I couldn't apply it and got the following error:

Applying: Issue #968: Kimchi is searching for 'undefined' VM
fatal: sha1 information is lacking or useless (ui/js/src/kimchi.guest_main.js).
Repository lacks necessary blobs to fall back on 3-way merge.
Cannot fall back to three-way merge.
Patch failed at 0001 Issue #968: Kimchi is searching for 'undefined' VM

**Comment by sstoppler** [comment] 2016-07-26 23:10
It turns out that another patch needed to be applied prior to the one for this bug.  After successfully applying the patch, I no longer see guestElem or templateStr undefined in the console.  I was never able to see isoInfo undefined so I can't say whether or not that still exists.

**Closed** 2016-07-27 20:38 UTC
Labels: bug, UI
