### ISSUE TITLE
FC20: model tests fails for deleting vm

### ISSUE THREAD

**Issue by lvroyce** [kimchi-project/kimchi#567] opened 2015-01-13 08:33 UTC
======================================================================
ERROR: test_delete_running_vm (test_model.ModelTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_model.py", line 1334, in test_delete_running_vm
    inst.vm_start(u'kīмсhī-∨м')
  File "/home/royce/kimchi-use-bisect/kimchi/src/kimchi/model/vms.py", line 851, in start
    {'name': name, 'err': e.get_error_message()})
OperationFailed: KCHVM0019E: Unable to start virtual machine k\u012b\u043c\u0441h\u012b-\u2228\u043c. Details: Invalid argument

**Comment by cd1** [comment] 2015-01-13 11:28
This is a duplicate of issue #450.

Also, please report issues for Fedora 21, which is the latest version of that distro.

**Closed** 2015-02-12 16:10 UTC
