### ISSUE TITLE
Added network not appearing in VM

### ISSUE THREAD

**Issue by fegul** [kimchi-project/kimchi#1098] opened 2016-12-24 06:08 UTC
Running the latest versions of Wok, Gingerbase, Ginger, and Kimchi.

I'm looking to put my VMs on the main network that the host is plugged into (bridging) and I've done the following:

1. Added a new network with a type of Macvtap and started it from the network page
2. Edited the guest VM (Ubuntu Server 16.04) I want to add the bridged network to and added it (so there are two networks for the guest VM: the default NAT one that came with the VM when it was created and the bridge one that I created)
3. Started the guest VM

Expected behavior should be that there are now three interfaces in the guest VM (loopback, NAT, and the bridge) however there are still only two networks (loopback and NAT) and the bridge is nowhere to be found.

**Comment by ramonmedeiros** [comment] 2017-02-10 12:19
Hi, just tried to reproduce with Fedora 25 and Ubuntu 16.10 and did not found the error.

Steps:

1) Create macvtap based on my ethernet interface
2) Add to VM
3) Poweron VM and run ifconfig -a 

What i saw is that ifconfig is returning just one interface, because the added on starts off. Can you confirm it?

**Comment by ramonmedeiros** [comment] 2017-02-10 16:30
Just tested with Ubuntu 16.04 as guests. Same behaviour: after adding macvtap, can see it in guests by ifconfig -a.

I will close the issue. If it is reproducible, please reopen

**Closed by ramonmedeiros** 2017-02-10 16:30 UTC
