### ISSUE TITLE
Kimchi don't start on Centos 7.2

### ISSUE THREAD

**Issue by Ingvarhost** [kimchi-project/kimchi#845] opened 2016-02-20 12:19 UTC
I have KVM host with Centos 7.2. When I install Wok 2.0 and Ginger-base 2.0 from rpms, the service wokd correctly start and I may login to the web interface. After what I install Kimchi 2.0 and wokd don't starting. System log:

```
systemd[1]: Started Wok - Webserver Originated from Kimchi.
systemd[1]: Starting Wok - Webserver Originated from Kimchi...
polkitd[877]: Unregistered Authentication Agent for unix-process:3417:695462 (system bus name :1.86, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
wokd[3422]: nginx: [emerg] bind() to 0.0.0.0:8001 failed (98: Address already in use)
wokd[3422]: nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
wokd[3422]: nginx: [emerg] bind() to 0.0.0.0:8001 failed (98: Address already in use)
wokd[3422]: nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
wokd[3422]: nginx: [emerg] bind() to 0.0.0.0:8001 failed (98: Address already in use)
wokd[3422]: nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
wokd[3422]: nginx: [emerg] bind() to 0.0.0.0:8001 failed (98: Address already in use)
wokd[3422]: nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
wokd[3422]: nginx: [emerg] bind() to 0.0.0.0:8001 failed (98: Address already in use)
wokd[3422]: nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
wokd[3422]: nginx: [emerg] still could not bind()
wokd[3422]: libvirt: Network Driver error : Network not found: no network with matching name 'default'
wokd[3422]: WARNING: no 'numpy' module, HyBi protocol will be slower
libvirtd[1206]: End of file while reading data: Input/output error
systemd[1]: wokd.service: main process exited, code=exited, status=1/FAILURE
kill[3435]: Usage:
kill[3435]: kill [options] <pid|name> [...]
kill[3435]: Options:
kill[3435]: -a, --all              do not restrict the name-to-pid conversion to processes
kill[3435]: with the same uid as the present process
kill[3435]: -s, --signal <sig>     send specified signal
kill[3435]: -q, --queue <sig>      use sigqueue(2) rather than kill(2)
kill[3435]: -p, --pid              print pids without signaling them
kill[3435]: -l, --list [=<signal>] list signal names, or convert one to a name
kill[3435]: -L, --table            list signal names and numbers
kill[3435]: -h, --help     display this help and exit
kill[3435]: -V, --version  output version information and exit
kill[3435]: For more details see kill(1).
systemd[1]: wokd.service: control process exited, code=exited status=1
systemd[1]: Unit wokd.service entered failed state.
systemd[1]: wokd.service failed.
```

**Comment by avs262** [comment] 2016-02-23 23:09
According to your logs port 8000 and 8001 are already in use.

**Comment by Ingvarhost** [comment] 2016-02-24 08:09
This ports using by nginx, which started by wokd.```
tcp        0      0 0.0.0.0:8000            0.0.0.0:*               LISTEN      3293/nginx: master
tcp        0      0 0.0.0.0:8001            0.0.0.0:*               LISTEN      3293/nginx: master
```
Before I install kimchi, wokd work normally. When I install kimchi rpm, then systemctl tells me: "wokd.service changed on disk. Run 'systemctl daemon-reload' to reload units." After reload wokd don't work. So, I think, kimchi broke the wokd unit.

**Comment by alinefm** [comment] 2016-03-08 18:28
Hi @Ingvarhost !

Kimchi package installs a new systemd file, /etc/systemd/system/wokd.service.d/kimchi.conf, to make sure libvirt service is up and running.

I am not familiar with CentOS, but I think you need to enable the kimchi service on systemd in a similar way you did for wokd.

The contend of /etc/systemd/system/wokd.service.d/kimchi.conf
`[Unit]                                                                          
Requires=libvirtd.service wokd.service                                          
After=libvirtd.service wokd.service                                             
                                                                                
[Service]                                                                       
Nice=0                                                                          
PrivateTmp=yes`

**Comment by alinefm** [comment] 2016-03-08 18:46
@pvital Please, try to reproduce it and provide feedback.

**Comment by Truja** [comment] 2016-03-08 18:49
I think the following scenarios worth test:

1 - Install wok rpm and run it, then install kimchi rpm
2 - Install wok rpm and run it, then install ginger rpm
3 - Install wok and kimchi rpms  and run it, then update kimchi rpm
4 - Install wok and ginger rpms and run it, then update ginger rpm

**Comment by pvital** [comment] 2016-03-28 17:30
Just tested Wok, Gingerbase and Kimchi 2.1.0 (released last Friday) RPM files in a fresh CentOS 7.2 system. I could, with no problems, install all packages and start up the service.

To reproduce my tests:

1. install wok RPM and start wok.service
2. install gingerbase RPM and restart wok.service
3. install kimchi RPM and restart wokd.service

One important thing to mention is that, after Kimchi installation, you must reload systemd daemon due to the wokd.service configuration modifications made by and Kimchi RPM. This reload must be executed even if you're installing Kimchi for the first time.

So, after install Kimchi RPM, do the following.

```
$ sudo systemctl daemon-reload
$ sudo systemctl restart wokd.service
$ sudo systemctl -l status wokd.service
● wokd.service - Wok - Webserver Originated from Kimchi
   Loaded: loaded (/usr/lib/systemd/system/wokd.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/wokd.service.d
           └─kimchi.conf
   Active: active (running) since Mon 2016-03-28 14:10:38 BRT; 4s ago
  Process: 18649 ExecStop=/bin/kill -TERM $MAINPID (code=exited, status=0/SUCCESS)
 Main PID: 18680 (python2)
   CGroup: /system.slice/wokd.service
           ├─18680 python2 /usr/bin/wokd
           ├─18688 nginx: master process nginx -c /etc/nginx/conf.d/wok.con
           ├─18690 nginx: worker process
           └─18783 python2 /usr/bin/wokd

Mar 28 14:10:38 localhost.localdomain systemd[1]: Started Wok - Webserver Originated from Kimchi.
Mar 28 14:10:38 localhost.localdomain systemd[1]: Starting Wok - Webserver Originated from Kimchi...
Mar 28 14:10:39 localhost.localdomain wokd[18680]: libvirt: Storage Driver error : Storage pool not found: no storage pool with matching name 'default'
Mar 28 14:10:39 localhost.localdomain wokd[18680]: libvirt: Storage Driver error : Storage pool not found: no storage pool with matching name 'ISO'
Mar 28 14:10:39 localhost.localdomain wokd[18680]: WARNING: no 'numpy' module, HyBi protocol will be slower
$
```

**Comment by alanlaird** [comment] 2016-04-11 01:58
Hello @pvital, could you provide the URLs you are installing the RPMs from to get your result?  I'm seeing what looks like an nginx config issue in the list of RPMs published for the 2.1 release here:
http://kimchi-project.github.io/wok/downloads/wok-2.1.0-0.el7.noarch.rpm 
http://kimchi-project.github.io/gingerbase/downloads/ginger-base-2.1.0-0.el7.noarch.rpm http://kimchi-project.github.io/kimchi/downloads/kimchi-2.1.0-0.el7.noarch.rpm

I'm new to github pages.  Is github building these RPMs?  Where are the specs for these?

Thanks,

Alan

**Comment by pvital** [comment] 2016-04-11 13:23
Hello @alanlaird 

I used the same URLs you posted to install and run Wok, Gingerbase and Kimchi on my CentOS system. Follow are the md5sum of the RPM files I downloaded and installed:

```
[test@localhost ~]$ md5sum *.rpm
76621c53c9601cc9e1a374b10686c5e4  ginger-base-2.1.0-0.el7.noarch.rpm
7e02409c622c9b144618549dd9896afa  kimchi-2.1.0-0.el7.noarch.rpm
34adae3d370ed9a8f33371cef18373e5  wok-2.1.0-0.el7.noarch.rpm
[test@localhost ~]$ $ uname -a
Linux localhost.localdomain 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[test@localhost ~]$ cat /etc/centos-release
CentOS Linux release 7.2.1511 (Core) 
[test@localhost ~]$ 
```

I installed them, using yum to resolve all necessary dependencies my system needed. 

The RPM files were not built by github or any service provided by github pages. The maintainers of the projects built them in specific systems. The specs for each one of the RPMs are available in the projects source tree, under contrib directory.

**Comment by pvital** [comment] 2016-05-24 14:51
@alinefm since we don't have any activity on this issue for more than 1.5 months, I guess you can close it.

**Comment by alanlaird** [comment] 2016-05-31 22:42
@pvital Hi, Perhaps I have a different version of 7.2 or repos enabled.  Do you recall what you were testing on and what repos were enabled?

**Comment by olidietzel** [comment] 2016-06-29 18:46
Had the same problem with 2.2.0, solved it by activating rc.local and appending a "systemctl restart wokd.service" in it.

Maybe the wokd starter needs a dependency like "After=network.target" in its systemd script. Trying to start a web server before network.target mostly ends unlucky and on a fast box you are really fast out of luck without such a dependency.

I preferred the oldschool rc.local workaround since its rpm update fool proof. :)

**Comment by thesabbir** [comment] 2016-07-24 18:42
Same here:

```
nginx: [emerg] bind() to 0.0.0.0:8001 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8001 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8001 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8001 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8001 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
nginx: [emerg] still could not bind()
```

App is running though at 8010:
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 localhost:8010          0.0.0.0:*               LISTEN      4483/python2
tcp        0      0 0.0.0.0:ssh             0.0.0.0:*               LISTEN      11648/sshd
tcp        0      0 localhost:smtp          0.0.0.0:*               LISTEN      1921/master
tcp        0      0 0.0.0.0:irdmi           0.0.0.0:*               LISTEN      4485/nginx: master
tcp        0      0 0.0.0.0:vcom-tunnel     0.0.0.0:*               LISTEN      4485/nginx: master
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN      11648/sshd
tcp6       0      0 localhost:smtp          [::]:*                  LISTEN      1921/master
udp        0      0 0.0.0.0:43985           0.0.0.0:*                           909/dhclient
udp        0      0 0.0.0.0:27734           0.0.0.0:*                           913/dhclient
udp        0      0 0.0.0.0:bootpc          0.0.0.0:*                           909/dhclient
udp6       0      0 [::]:22453              [::]:*                              909/dhclient
udp6       0      0 server:dhcpv6-client    [::]:*                              913/dhclient
udp6       0      0 [::]:22015              [::]:*                              913/dhclient
```

**Comment by pvital** [comment] 2016-10-10 10:40
There're new release (2.3.0) of Wok, Gingerbase and Kimchi available to download. Now, there is CentOS specific packages and you can use them. Could you please test this version? Please, install them in the following sequence:

http://bit.ly/get_wok
http://bit.ly/get_gingerbase
http://bit.ly/get_kimchi

**Comment by Ingvarhost** [comment] 2016-10-10 12:51
Hello @pvital!
I tested the new version of Wok, Gingerbase and Kimchi. All works correctly. Thanks!

**Closed** 2016-10-10 13:30 UTC
Labels: bug

**Comment by crosscutrat** [comment] 2016-12-06 21:31
These updates did not resolve the same issue for me.  I had to do two things:

1.  Disable selinux
vi /etc/selinux/config

2.  Open 8010 in firewall
firewall-cmd --get-active-zones
firewall-cmd --zone=public --add-port=8010/tcp --permanent
firewall-cmd --reload

**Comment by alinefm** [comment] 2016-12-07 13:36
Hi @crosscutrat 

You should not need to open 8010 port on firewall as it runs on localhost.

**Comment by crosscutrat** [comment] 2016-12-07 22:29
Very sorry.  That was a typo.  8001 was the port I had to open.

**Comment by mierea** [comment] 2017-06-04 21:09
I am having the issue described here on a fresh Centos install.

I used the following RPMs:
-rw-r--r--. 1 root root 283784 May  1 20:41 ginger-base.el7.centos.noarch.rpm
-rw-r--r--. 1 root root 436752 Mar 30 15:02 ginger.el7.centos.noarch.rpm
-rw-r--r--. 1 root root 676816 May 24 17:57 kimchi.el7.centos.noarch.rpm
-rw-r--r--. 1 root root 569564 May 24 18:02 wok.el7.centos.noarch.rpm

[root@kimchi ~]# uname -a
Linux kimchi 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux


[root@kimchi ~]# systemctl status wokd -l
● wokd.service - Wok - Webserver Originated from Kimchi
   Loaded: loaded (/usr/lib/systemd/system/wokd.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/wokd.service.d
           └─kimchi.conf
   Active: failed (Result: exit-code) since Sun 2017-06-04 22:58:14 CEST; 8min ago
     Docs: https://github.com/kimchi-project/wok/wiki
  Process: 13078 ExecStop=/bin/kill -TERM $MAINPID (code=exited, status=1/FAILURE)
  Process: 13071 ExecStart=/usr/bin/wokd (code=exited, status=1/FAILURE)
 Main PID: 13071 (code=exited, status=1/FAILURE)

Jun 04 22:58:14 kimchi kill[13078]: -s, --signal <sig>     send specified signal
Jun 04 22:58:14 kimchi kill[13078]: -q, --queue <sig>      use sigqueue(2) rather than kill(2)
Jun 04 22:58:14 kimchi kill[13078]: -p, --pid              print pids without signaling them
Jun 04 22:58:14 kimchi kill[13078]: -l, --list [=<signal>] list signal names, or convert one to a name
Jun 04 22:58:14 kimchi kill[13078]: -L, --table            list signal names and numbers
Jun 04 22:58:14 kimchi kill[13078]: -h, --help     display this help and exit
Jun 04 22:58:14 kimchi kill[13078]: -V, --version  output version information and exit
Jun 04 22:58:14 kimchi kill[13078]: For more details see kill(1).
Jun 04 22:58:14 kimchi systemd[1]: Unit wokd.service entered failed state.
Jun 04 22:58:14 kimchi systemd[1]: wokd.service failed.

Logs in /var/log/wok are empty.

In /var/log/messages:

Jun  4 22:58:10 kimchi systemd: Dependency After=wokd.service dropped from unit wokd.service
Jun  4 22:58:14 kimchi systemd: Started Wok - Webserver Originated from Kimchi.
Jun  4 22:58:14 kimchi systemd: Starting Wok - Webserver Originated from Kimchi...
Jun  4 22:58:14 kimchi wokd: WARNING: no 'numpy' module, HyBi protocol will be slower
Jun  4 22:58:14 kimchi wokd: Traceback (most recent call last):
Jun  4 22:58:14 kimchi wokd: File "/usr/bin/wokd", line 88, in <module>
Jun  4 22:58:14 kimchi wokd: sys.exit(main(sys.argv[1:]))
Jun  4 22:58:14 kimchi wokd: File "/usr/bin/wokd", line 85, in main
Jun  4 22:58:14 kimchi wokd: wok.server.main(options)
Jun  4 22:58:14 kimchi wokd: File "/usr/lib/python2.7/site-packages/wok/server.py", line 190, in main
Jun  4 22:58:14 kimchi wokd: srv = Server(options)
Jun  4 22:58:14 kimchi wokd: File "/usr/lib/python2.7/site-packages/wok/server.py", line 161, in __init__
Jun  4 22:58:14 kimchi wokd: cherrypy.tree.mount(WokRoot(model.Model(), dev_env),
Jun  4 22:58:14 kimchi wokd: File "/usr/lib/python2.7/site-packages/wok/model/model.py", line 32, in __init__
Jun  4 22:58:14 kimchi wokd: models = get_all_model_instances(__name__, __file__, kargs)
Jun  4 22:58:14 kimchi wokd: File "/usr/lib/python2.7/site-packages/wok/utils.py", line 548, in get_all_model_instances
Jun  4 22:58:14 kimchi wokd: models.append(instance(**kwargs))
Jun  4 22:58:14 kimchi wokd: File "/usr/lib/python2.7/site-packages/wok/model/peers.py", line 33, in __init__
Jun  4 22:58:14 kimchi wokd: if not config.get('server', 'federation') == 'off':
Jun  4 22:58:14 kimchi wokd: File "/usr/lib64/python2.7/ConfigParser.py", line 618, in get
Jun  4 22:58:14 kimchi wokd: raise NoOptionError(option, section)
Jun  4 22:58:14 kimchi wokd: ConfigParser.NoOptionError: No option 'federation' in section: 'server'
Jun  4 22:58:14 kimchi systemd: wokd.service: main process exited, code=exited, status=1/FAILURE
Jun  4 22:58:14 kimchi kill: Usage:
Jun  4 22:58:14 kimchi systemd: wokd.service: control process exited, code=exited status=1
Jun  4 22:58:14 kimchi kill: kill [options] <pid|name> [...]
Jun  4 22:58:14 kimchi kill: Options:
Jun  4 22:58:14 kimchi kill: -a, --all              do not restrict the name-to-pid conversion to processes
Jun  4 22:58:14 kimchi kill: with the same uid as the present process
Jun  4 22:58:14 kimchi kill: -s, --signal <sig>     send specified signal
Jun  4 22:58:14 kimchi kill: -q, --queue <sig>      use sigqueue(2) rather than kill(2)
Jun  4 22:58:14 kimchi kill: -p, --pid              print pids without signaling them
Jun  4 22:58:14 kimchi kill: -l, --list [=<signal>] list signal names, or convert one to a name
Jun  4 22:58:14 kimchi kill: -L, --table            list signal names and numbers
Jun  4 22:58:14 kimchi kill: -h, --help     display this help and exit
Jun  4 22:58:14 kimchi kill: -V, --version  output version information and exit
Jun  4 22:58:14 kimchi kill: For more details see kill(1).
Jun  4 22:58:14 kimchi systemd: Unit wokd.service entered failed state.
Jun  4 22:58:14 kimchi systemd: wokd.service failed.

For now I will switch to ubuntu. Would be nice to know what I am doing wrong on Centos.

Thanx.

**Comment by alinefm** [comment] 2017-06-06 15:30
@mierea Thanks for reporting that. I will take a look soon and turn back to you.
