### ISSUE TITLE
Possible with apache?

### ISSUE THREAD

**Issue by daniel-lucio** [kimchi-project/kimchi#668] opened 2015-06-18 01:20 UTC
I am not a python coder, but i was reading some portions of code, and I found it looks for specific nginx files.

**Comment by danielhb** [comment] 2015-06-24 22:53
Yes, kimchi uses nginx ans a proxy and it sets up nginx configuration files according to the command line options.

**Comment by daniel-lucio** [comment] 2015-06-25 01:01
Le 24 juin 2015, 15:53:35 Daniel Henrique Barboza a écrit :
> Yes, kimchi uses nginx ans a proxy and it sets up nginx 
configuration files
> according to the command line options.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/kimchi-project/kimchi/issues/668#issuecomment-115037517


What is the command line option to start without nginx

LD

**Comment by cd1** [comment] 2015-06-30 13:35
There's no way of disabling nginx when running Kimchi.

**Comment by cd1** [comment] 2015-06-30 13:37
This issue is a duplicate of #570.

**Closed by cd1** 2015-06-30 13:37 UTC
