### ISSUE TITLE
Tests fail with 201!=500 on Fedora 20

### ISSUE THREAD

**Issue by clnperez** [kimchi-project/kimchi#590] opened 2015-02-06 15:54 UTC
Ran 162 tests in 496.924s
FAILED (failures=22, errors=8, skipped=3)

Multiple tests fail with the reason: AssertionError: 201 != 500. For example:

===========================================
FAIL: test_vm_storage_devices (test_rest.RestTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_rest.py", line 566, in test_vm_storage_devices
    self.assertEquals(201, resp.status)
AssertionError: 201 != 500

I haven't been able to get to the bottom of these failures. Here's an interesting traceback I see for some tests:
======================================================================
ERROR: test_vm_info (test_mockmodel.MockModelTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_mockmodel.py", line 212, in test_vm_info
    model.vms_create({'name': u'test-vm', 'template': '/templates/test'})
  File "/home/christy/git/kimchi-upstream/src/kimchi/model/vms.py", line 247, in create
    self.caps.metadata_support)
  File "/home/christy/git/kimchi-upstream/src/kimchi/model/vms.py", line 629, in vm_update_os_metadata
    set_metadata_node(dom, os_elem, metadata_support)
  File "/home/christy/git/kimchi-upstream/src/kimchi/model/utils.py", line 121, in set_metadata_node
    flags=get_vm_config_flag(dom, mode))
  File "/home/christy/git/kimchi-upstream/src/kimchi/model/libvirtconnection.py", line 66, in wrapper
    ret = f(*args, **kwargs)
  File "/home/christy/git/kimchi-upstream/src/kimchi/model/libvirtconnection.py", line 66, in wrapper
    ret = f(*args, **kwargs)
  File "/home/christy/git/kimchi-upstream/src/kimchi/model/libvirtconnection.py", line 66, in wrapper
    ret = f(*args, **kwargs)
  File "/home/christy/git/kimchi-upstream/src/kimchi/model/libvirtconnection.py", line 66, in wrapper
    ret = f(*args, **kwargs)
  File "/home/christy/git/kimchi-upstream/src/kimchi/model/libvirtconnection.py", line 66, in wrapper
    ret = f(*args, **kwargs)
  File "/home/christy/git/kimchi-upstream/src/kimchi/model/libvirtconnection.py", line 66, in wrapper
    ret = f(*args, **kwargs)
  File "/home/christy/git/kimchi-upstream/src/kimchi/model/libvirtconnection.py", line 66, in wrapper
    ret = f(*args, **kwargs)
  File "/home/christy/git/kimchi-upstream/src/kimchi/model/libvirtconnection.py", line 66, in wrapper
    ret = f(*args, **kwargs)
  File "/home/christy/git/kimchi-upstream/src/kimchi/model/libvirtconnection.py", line 66, in wrapper
    ret = f(*args, **kwargs)
  File "/home/christy/git/kimchi-upstream/src/kimchi/model/libvirtconnection.py", line 66, in wrapper
    ret = f(*args, **kwargs)
  File "/home/christy/git/kimchi-upstream/src/kimchi/model/libvirtconnection.py", line 66, in wrapper
    ret = f(*args, **kwargs)
  File "/home/christy/git/kimchi-upstream/src/kimchi/model/libvirtconnection.py", line 66, in wrapper
    ret = f(*args, **kwargs)
  File "/home/christy/git/kimchi-upstream/src/kimchi/model/libvirtconnection.py", line 66, in wrapper
    ret = f(*args, **kwargs)
  File "/home/christy/git/kimchi-upstream/src/kimchi/model/libvirtconnection.py", line 66, in wrapper
    ret = f(*args, **kwargs)
  File "/home/christy/git/kimchi-upstream/src/kimchi/model/libvirtconnection.py", line 66, in wrapper
    ret = f(*args, **kwargs)
  File "/home/christy/git/kimchi-upstream/src/kimchi/model/libvirtconnection.py", line 66, in wrapper
    ret = f(*args, **kwargs)
  File "/home/christy/git/kimchi-upstream/src/kimchi/model/libvirtconnection.py", line 66, in wrapper
    ret = f(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 1607, in setMetadata
    if ret == -1: raise libvirtError ('virDomainSetMetadata() failed', dom=self)
libvirtError: cannot create config directory '(null)': Bad address

I also see that one for ERROR: test_nonroot_access (test_authorization.AuthorizationTests), and ERROR: test_use_test_host (test_model.ModelTests). I see the same stack trace multiple times throughout the tests, so it may or may not be related to the 201!=500 failures.

==========

$ cat /etc/issue
Fedora release 20 (Heisenbug)

$ uname -a
Linux christy-toshiba 3.17.8-200.fc20.x86_64 #1 SMP

$ rpm -q libvirt
libvirt-1.1.3.8-1.fc20.x86_64

**Comment by alinefm** [comment] 2015-02-06 16:27
@clnperez Please, verify on Fedora 21 as Fedora 20 is not in our test map anymore.

**Comment by clnperez** [comment] 2015-02-06 21:26
FAILED (failures=3, errors=4, skipped=3) after updating. I'll see if I can get those to go away, too. There were a few network issues due to my config that I could make go away, but the ones left aren't obvious.

**Comment by clnperez** [comment] 2015-02-06 21:58
======================================================
FAIL: test_network_lifecycle (test_model_network.NetworkTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_model_network.py", line 144, in test_network_lifecycle
    _do_network_test(self, model, net)
  File "test_model_network.py", line 81, in _do_network_test
    self.assertEquals(200, resp.status)
AssertionError: 200 != 500
----------------------------------------------------------------------
Ran 1 test in 1.622s
FAILED (failures=1)

There are still a couple of others that I can open separate issues for, if you'd prefer.

**Comment by clnperez** [comment] 2015-02-10 23:10
The others seems to be covered in issue #493

**Comment by alinefm** [comment] 2015-02-11 19:44
@clnperez So can we close this issue?

**Comment by clnperez** [comment] 2015-02-11 20:07
@alinefm, I think we still need this for the 200 != 500 error.

**Comment by cd1** [comment] 2015-02-17 21:52
The function `test_network_lifecycle` (in test_model_network.py) has a loop which creates a few networks in order to test them later. However, each of those loop iteration tests leaks a network bridge on the system. So when the next iteration test is executed, a bridge already exists and the issue described here happens. The exception actually happens when the test network is activated, and then the following error is displayed:

```
libvirt:  error : Unable to create bridge virbr1: File exists
```

And that makes the request return 500 instead of 200.

I tried removing all but one of those loop iterations (i.e. I left only one network to be tested) and that test case ran fine. However, the bridge still leaked. Which is really bad (and is what's causing this issue) because we're leaving a new bridge on the system after the user runs our tests.

I don't know if this is related to issue #556, but at least it seems to be.

**Comment by lvroyce** [comment] 2015-03-11 09:04
I reproduce when running all tests using ./run_tests.sh  with Ubuntu 14.04

**Comment by alinefm** [comment] 2015-03-17 20:24
I am not able to reproduce it on Ubuntu 14.10

    alinefm@alinefm:~/kimchi/tests$ brctl show
bridge name	bridge id		STP enabled	interfaces
virbr0		8000.000000000000	yes		

    alinefm@alinefm:~/kimchi/tests$ sudo ./run_tests.sh test_model_network.NetworkTests.test_network_lifecycle
Loading AptUpdate features.
[17/Mar/2015:17:22:46] ENGINE Bus STARTING
[17/Mar/2015:17:22:46] ENGINE Started monitor thread 'Autoreloader'.
[17/Mar/2015:17:22:46] ENGINE Serving on http://127.0.0.1:55637
*** Running feature tests ***
libvirt:  error : internal error: Child process (/sbin/showmount --no-headers --exports localhost) unexpected exit status 1: clnt_create: RPC: Program not registered
internal error: Child process (/sbin/showmount --no-headers --exports localhost) unexpected exit status 1: clnt_create: RPC: Program not registered

*** Feature tests completed ***
[17/Mar/2015:17:22:49] ENGINE Bus STARTED
[17/Mar/2015:17:22:49] ENGINE Started monitor thread 'Session cleanup'.
127.0.0.1 - - [17/Mar/2015:17:22:49] "GET /interfaces?type=nic HTTP/1.0" 200 105 "" ""
127.0.0.1 - - [17/Mar/2015:17:22:49] "POST /networks HTTP/1.0" 201 294 "" ""
127.0.0.1 - - [17/Mar/2015:17:22:49] "GET /networks/k\xc4\xab\xd0\xbc\xd1\x81h\xc4\xab-\xd0\xbfet HTTP/1.0" 200 294 "" ""
127.0.0.1 - - [17/Mar/2015:17:22:49] "GET /networks/k%C4%AB%D0%BC%D1%81h%C4%AB-%D0%BFet HTTP/1.0" 200 292 "" ""
127.0.0.1 - - [17/Mar/2015:17:22:49] "GET /networks/k\xc4\xab\xd0\xbc\xd1\x81h\xc4\xab-\xd0\xbfet HTTP/1.0" 200 292 "" ""
127.0.0.1 - - [17/Mar/2015:17:22:49] "GET /networks/k%C4%AB%D0%BC%D1%81h%C4%AB-%D0%BFet HTTP/1.0" 200 294 "" ""
127.0.0.1 - - [17/Mar/2015:17:22:49] "GET /networks/k\xc4\xab\xd0\xbc\xd1\x81h\xc4\xab-\xd0\xbfet HTTP/1.0" 200 294 "" ""
127.0.0.1 - - [17/Mar/2015:17:22:49] "DELETE /networks/k\xc4\xab\xd0\xbc\xd1\x81h\xc4\xab-\xd0\xbfet HTTP/1.0" 204 - "" ""
libvirt: Network Driver error : Network not found: no network with matching name 'kīмсhī-пet'
libvirt: Network Driver error : Network not found: no network with matching name 'kīмсhī-пet'
127.0.0.1 - - [17/Mar/2015:17:22:49] "POST /networks HTTP/1.0" 201 265 "" ""
127.0.0.1 - - [17/Mar/2015:17:22:50] "GET /networks/nat-network HTTP/1.0" 200 265 "" ""
127.0.0.1 - - [17/Mar/2015:17:22:50] "GET /networks/nat-network HTTP/1.0" 200 263 "" ""
127.0.0.1 - - [17/Mar/2015:17:22:50] "GET /networks/nat-network HTTP/1.0" 200 263 "" ""
127.0.0.1 - - [17/Mar/2015:17:22:50] "GET /networks/nat-network HTTP/1.0" 200 265 "" ""
127.0.0.1 - - [17/Mar/2015:17:22:50] "GET /networks/nat-network HTTP/1.0" 200 265 "" ""
127.0.0.1 - - [17/Mar/2015:17:22:50] "DELETE /networks/nat-network HTTP/1.0" 204 - "" ""
libvirt: Network Driver error : Network not found: no network with matching name 'nat-network'
libvirt: Network Driver error : Network not found: no network with matching name 'nat-network'
127.0.0.1 - - [17/Mar/2015:17:22:50] "POST /networks HTTP/1.0" 201 268 "" ""
127.0.0.1 - - [17/Mar/2015:17:22:50] "GET /networks/subnet-network HTTP/1.0" 200 268 "" ""
127.0.0.1 - - [17/Mar/2015:17:22:51] "GET /networks/subnet-network HTTP/1.0" 200 266 "" ""
127.0.0.1 - - [17/Mar/2015:17:22:51] "GET /networks/subnet-network HTTP/1.0" 200 266 "" ""
127.0.0.1 - - [17/Mar/2015:17:22:51] "GET /networks/subnet-network HTTP/1.0" 200 268 "" ""
127.0.0.1 - - [17/Mar/2015:17:22:51] "GET /networks/subnet-network HTTP/1.0" 200 268 "" ""
127.0.0.1 - - [17/Mar/2015:17:22:51] "DELETE /networks/subnet-network HTTP/1.0" 204 - "" ""
libvirt: Network Driver error : Network not found: no network with matching name 'subnet-network'
libvirt: Network Driver error : Network not found: no network with matching name 'subnet-network'
127.0.0.1 - - [17/Mar/2015:17:22:51] "POST /networks HTTP/1.0" 201 229 "" ""
127.0.0.1 - - [17/Mar/2015:17:22:51] "GET /networks/bridge-network HTTP/1.0" 200 229 "" ""
127.0.0.1 - - [17/Mar/2015:17:22:51] "GET /networks/bridge-network HTTP/1.0" 200 227 "" ""
127.0.0.1 - - [17/Mar/2015:17:22:51] "GET /networks/bridge-network HTTP/1.0" 200 227 "" ""
127.0.0.1 - - [17/Mar/2015:17:22:51] "GET /networks/bridge-network HTTP/1.0" 200 229 "" ""
127.0.0.1 - - [17/Mar/2015:17:22:51] "GET /networks/bridge-network HTTP/1.0" 200 229 "" ""
libvirt: Network Driver error : internal error: network 'bridge-network' does not have a bridge name.
127.0.0.1 - - [17/Mar/2015:17:22:51] "DELETE /networks/bridge-network HTTP/1.0" 204 - "" ""
libvirt: Network Driver error : Network not found: no network with matching name 'bridge-network'
libvirt: Network Driver error : Network not found: no network with matching name 'bridge-network'
.[17/Mar/2015:17:22:51] ENGINE Bus STOPPING
[17/Mar/2015:17:22:51] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 55637)) shut down
libvirt: QEMU Driver error : Domain not found: no domain with matching name 'FEATURETEST_VM'
libvirt: Storage Driver error : Storage pool not found: no storage pool with matching name 'FEATURETEST_POOL'
[17/Mar/2015:17:22:51] ENGINE Stopped thread 'Autoreloader'.
[17/Mar/2015:17:22:51] ENGINE Stopped thread 'Session cleanup'.
[17/Mar/2015:17:22:51] ENGINE Bus STOPPED
[17/Mar/2015:17:22:51] ENGINE Bus EXITING
[17/Mar/2015:17:22:51] ENGINE Waiting for child threads to terminate...
[17/Mar/2015:17:22:51] ENGINE Bus EXITED

----------------------------------------------------------------------
Ran 1 test in 5.610s

OK

    alinefm@alinefm:~/kimchi/tests$ brctl show
bridge name	bridge id		STP enabled	interfaces
virbr0		8000.000000000000	yes

**Comment by clnperez** [comment] 2015-03-18 13:35
On Fedora 21, If I run it once, it passes. If I run it the 2nd time, it will fail. Did you try twice back to back?

**Comment by alinefm** [comment] 2016-07-06 22:16
All tests are passing on Fedora 23.
I will close this issue.

**Closed by alinefm** 2016-07-06 22:16 UTC
