### ISSUE TITLE
RHEL7: Unable to add/edit package repository

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/kimchi#519] opened 2014-12-03 13:51 UTC
1. Login as admin
2. Swtich to Host Tab
3. Add new repository
4. Enter the URL: http://download.fedoraproject.org/pub/epel/7/SRPMS
5. An error will be displayed: "KCHUTILS0001E: Invalid URI http://download.fedoraproject.org/pub/epel/7/SRPMS"

The same error occurs when I try to update an existing repository and provide the above URL as "Base URL"

If I try to use the above URL to update a "Mirror list URL" in a existing repository I got the following error: "KCHREPOS0002E: Repository URL must be an http://, ftp:// or file:// URL."
The same happens when I don't change any repository information and only hit "Save" button.

**Comment by cd1** [comment] 2015-03-17 12:59
Duplicate of #617.

**Closed by cd1** 2015-03-17 12:59 UTC
Labels: duplicated
