### ISSUE TITLE
WOK: Help button displays blank page

### ISSUE THREAD

**Issue by jay-katta** [kimchi-project/kimchi#705] opened 2015-07-17 11:29 UTC
Environment: x86
Operating system: Ubuntu
Browser: Mozilla Firefox
Steps performed:
1. Installed WOK (https://github.com/kimchi-project/kimchi/tree/wok)
2. Started wokd daemon
3. From browser launched https://127.0.0.1:8001
4. Login screen displayed
5. Entered userid and password
6. WOK web page displayed
7. Clicked on Help button.
Problem: Help button displays blank page

**Comment by samhenri** [comment] 2015-07-21 15:00
Unable to reproduce it. Are you able to open the help pages directly from the URL?

https://127.0.0.1:8001/plugins/kimchi/help/en_US/host.html
https://127.0.0.1:8001/plugins/kimchi/help/en_US/guests.html
https://127.0.0.1:8001/plugins/kimchi/help/en_US/templates.html
https://127.0.0.1:8001/plugins/kimchi/help/en_US/storage.html
https://127.0.0.1:8001/plugins/kimchi/help/en_US/network.html
https://127.0.0.1:8001/plugins/ginger/help/en_US/host-admin.html

**Comment by jay-katta** [comment] 2015-07-22 13:29
To reproduce the issue, Install only WOK (with out kimchi-wok/ginger-wok plugin) and click on HELP button. It displays blank page.

If I install kimchi-wok and ginger-wok plugins, I am able to open all URLs -
https://127.0.0.1:8001/plugins/kimchi/help/en_US/host.html
https://127.0.0.1:8001/plugins/kimchi/help/en_US/guests.html
https://127.0.0.1:8001/plugins/kimchi/help/en_US/templates.html
https://127.0.0.1:8001/plugins/kimchi/help/en_US/storage.html
https://127.0.0.1:8001/plugins/kimchi/help/en_US/network.html
https://127.0.0.1:8001/plugins/ginger/help/en_US/host-admin.html

**Comment by lcorreia** [comment] 2015-08-04 16:46
That behaviour is expected for now until a help page for wok is created, if necessary. One idea is to show a welcome page when no plugin is installed.

The index of all help pages was removed because kimchi was transformed into a plugin and doesn't have a main page anymore.

**Comment by chandrureddy** [comment] 2015-08-07 06:04
Then in this case I would propose to remove the Help from the wok base frame work UI

**Comment by alinefm** [comment] 2015-12-03 17:09
I was able to reproduce it while running wok + ginger + kimchi.
On Guests tab, when I try to open the help page I got a blank window.

I am moving this issue to Wok repository: https://github.com/kimchi-project/wok/issues/6

**Closed by alinefm** 2015-12-03 17:09 UTC
Labels: wok
