### ISSUE TITLE
Error shown on clicking "Edit" button for NAT/isolated virtual networks

### ISSUE THREAD

**Issue by lcorreia** [kimchi-project/kimchi#1033] opened 2016-09-14 19:04 UTC
The following message is showed on error log when clicking on Edit button for a NAT/isolated network:
KCHIFACE0001E: Interface virbr1 does not exist

**Comment by lcorreia** [comment] 2017-03-17 18:50
Reproducible on Ubuntu 16.10

**Comment by alinefm** [comment] 2017-03-27 17:33
I am unable to reproduce that in my Ubuntu 16.10 system.
I could create/edit/stop/delete a NAT/isolated network without problems.

I am closing this bug by now. Please, feel free to reopen if the problem persists to you.

**Closed by alinefm** 2017-03-27 17:33 UTC
