### ISSUE TITLE
Unable to use Ubuntu 14.04 remote ISO suggested by Kimchi

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/kimchi#436] opened 2014-09-16 17:56 UTC
1. Create a template based on a remote ISO
2. Select "Ubuntu 14.04" suggested by Kimchi
3. Create a VM using this template
4. Start the VM

The VM will not start and due a problem with libvirt connection.
On libvirt log I get:

CURL: Error opening file: 
qemu-system-x86_64: -drive file=http://91.189.92.163:80/14.04/ubuntu-14.04-desktop-amd64.iso,if=none,id=drive-ide0-1-0,readonly=on,format=raw: could not open disk image http://91.189.92.163:80/14.04/ubuntu-14.04-desktop-amd64.iso: Invalid argument
2014-09-16 17:53:36.241+0000: shutting down

**Comment by cd1** [comment] 2015-02-18 15:47
I cannot reproduce this on Fedora 21. I created a VM (`remote-ubuntu`) as described above and it booted fine.

Here's the output of `GET /vms/remote-ubuntu/storages`:

```
[
  {
    "bus":"virtio",
    "path":"/var/lib/libvirt/images/d04f21b3-ac2d-4864-8813-96ea017a774c-0.img",
    "type":"disk",
    "dev":"vda",
    "format":"qcow2"
  },
  {
    "bus":"ide",
    "path":"http://releases.ubuntu.com:80/14.04/ubuntu-14.04-desktop-amd64.iso",
    "type":"cdrom",
    "dev":"hdc",
    "format":"raw"
  }
]
```

What OS are you using?

Do you know exactly which Linux distributions have a QEMU version which can't resolve hostnames correctly? You cited Fedora 20, but as we moved to Fedora 21 and don't support Fedora 20 anymore, are there any other distros which need that DNS feature built into Kimchi?

**Comment by danielhb** [comment] 2015-03-31 19:37
"Well, so I guess we need to change that approach."

I agree. I've tested this method in a random website and I got a 403 error. In other cases it goes back to the home page. And in other cases it works as intended by the approach. This means that Kimchi is taking a burden from qemu (= some qemu versions can't resolve hostnames) and turning it into its own (= some servers does not resolve URLs as predicted, thus remote ISO streaming in Kimchi fails randomly). This means that it's up to the webserver configuration the handling of such URLs with IP addresses in it.

In my honest opinion, Kimchi should drop this approach altogether, as it is proven to be randomly broken. If the host does not support iso streaming due to a qemu limitation with resolving host name, the user can either update his qemu version or download the ISO before using it. We can't solve a qemu problem by creating another one which we have absolutely no control.

**Closed** 2015-04-28 16:54 UTC
Labels: bug
