### ISSUE TITLE
Guest Edit: Add interface fail when 'isolated' or 'nat'(iPad, Chrome) -- Fedora20

### ISSUE THREAD

**Issue by YuXinHuo** [kimchi-project/kimchi#503] opened 2014-12-02 08:58 UTC

**Comment by cd1** [comment] 2015-03-25 13:48
We're closing this issue for lack of information. If someone is able to reproduce it and provide more details to us, we will reopen it.

**Closed by cd1** 2015-03-25 13:48 UTC
Labels: NEEDINFO

**Comment by lvroyce** [comment] 2015-04-01 09:40
Cannot reproduce it in current upstream code.
