### ISSUE TITLE
VLAN ID accepting only one digit

### ISSUE THREAD

**Issue by atreyeemukhopadhyay** [kimchi-project/kimchi#694] opened 2015-07-16 10:01 UTC
I tried creating Bridged network enabling VLAN. 
I am running kimchi https://9.152.151.63:8001/#tabs/host "mozilla firefox ESR 31.8.0 ESR".

Steps to reproduce 
1)Install and launch the kimchi. Login with admin user.
2)Navigate to 'Network' tab.
3)click '+' icon to add a network.
4)Select network type as 'Bridged', destination from the  drop-down option and check 'Enable VLAN'.
5)In VLAN ID field provide a value having more than one digit.

VLAN ID should accept value between 1 to 4094.
It's accepting only single digit.

![net1](https://cloud.githubusercontent.com/assets/13199397/8720301/89d895c6-2bcf-11e5-84a0-17cccaa5ca59.jpg)
![net2](https://cloud.githubusercontent.com/assets/13199397/8720308/948af73e-2bcf-11e5-8c94-24adcc045acb.jpg)

**Comment by ramonmedeiros** [comment] 2015-07-16 13:10
I just reproduced this issue using only one digit in my laptop, with NetworkManager enabled. Please, disabled NetworkManager and try again.

I tried this on RHEL 7.1, disabling NetworkManager and i successful created vlans with 1, 12, 123 and 1234.

**Comment by ramonmedeiros** [comment] 2015-08-18 11:29
Hi, any updates on this?

**Comment by chandrureddy** [comment] 2015-08-18 12:20
Hi,
I guess this is happens only on the s390 (Systemz) architecture since the interface name is too big.
Please do not take any action on this issue since issue is not reproducible on x86/PPC.

However we can keep this issue as it is and will be taken care in some time (support s390) if it make sense.

**Comment by ramonmedeiros** [comment] 2015-08-18 12:26
Can you try create a vlan by hand?

**Comment by chandrureddy** [comment] 2015-08-19 05:36
Sure Ramon. I am sure it works if the interface name is short.

**Comment by walterniklaus** [comment] 2015-08-20 13:45
From what I can see, the issue comes due to the fact that the initial interface name is already too long.
With RHEL7 due to the introduction of the concept of "Consistent Network Device Naming"
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Networking_Guide/ch-Consistent_Network_Device_Naming.html

the Interface Names are already getting to a string length of 13 Characters. Here the link to the section describing the System z name-scheme:  
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Networking_Guide/sec-Naming_Scheme_for_Network_Devices_Available_for_Linux_on_System_z.html

The overall limit for the name of a VLAN Device is 15 Characters: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Networking_Guide/sec-Naming_Scheme_for_VLAN_Interfaces.html.

With this restriction we will not be able to simply add the VLAN-ID at the end of the full interface name.

One possibility I could see for now is to eliminate some of the characters from the original interface name, characters which are not relevant for the device identification:
Interface Name                              VLAN-Id = abcd
enccw0.0.1234                              encw001234.abcd

**Comment by ramonmedeiros** [comment] 2015-09-08 17:30
I'm not understanding why this is happening, since the code truncate the interface name to avoid making it too big:

src/kimchi/model/networks.py:210
    def _create_vlan_tagged_bridge(self, interface, vlan_id):
        # Truncate the interface name if it exceeds 8 characters to make sure
        # the length of bridge name is less than 15 (its maximum value).
        br_name = KIMCHI_BRIDGE_PREFIX + interface[-8:] + '-' + vlan_id

Can you please give me access to this machine?
My email is ramonn at linux vnet ibm com

**Comment by alinefm** [comment] 2017-03-27 17:11
I am unable to reproduce that with the current upstream code.
I am closing this issue by now. Please, reopen if the problem persists to you.

**Closed by alinefm** 2017-03-27 17:11 UTC
Labels: bug
