### ISSUE TITLE
 wok framework is masking the exception while loading json

### ISSUE THREAD

**Issue by abhiramkulkarni** [kimchi-project/kimchi#752] opened 2015-11-05 20:16 UTC
Issue : While experimenting operation on PUT request, i mistakenly passed wrong json body.
Error message was being shown by wok framework as  
{
  "reason":"WOKAPI0006E: WOKAPI0006E",
  "code":"400 Bad Request"
}
Checked wok-error logs, no information was present.

On further debug found out that code is masking the exception and not logging it.
wok/control/utils.py in parse_request() method

Before
=====
        try:
            return json.loads(rawbody)
        except ValueError,ex:
            e = OperationFailed('WOKAPI0006E')
            raise cherrypy.HTTPError(400, e.message)

After
=====
        try:
            return json.loads(rawbody)
        except ValueError,ex:
            wok_log.error("Exception while loading the json:"+str(ex))
            e = OperationFailed('WOKAPI0006E')
            raise cherrypy.HTTPError(400, e.message)

After changes can see the exception message in logs.
Exception while loading the json:Expecting , delimiter: line 24 column 49 (char 1374)

Let me know if this is fine, will send the patch.
Thanks

**Comment by Truja** [comment] 2016-03-07 19:05
Hi Abhiram,
the root cause of this problem was a bit different. I have just sent a patch that fixed this  issue.
Thank you for reporting.

@alinefm I think we can close this issue with my latest patch

**Comment by alinefm** [comment] 2016-03-09 18:48
Fixed by https://github.com/kimchi-project/wok/commit/f87d5064c4020cd4bfeab1c610814fc832e96538

**Closed by alinefm** 2016-03-09 18:48 UTC
Labels: bug
